### PR TITLE
Title favicon

### PR DESCRIPTION
**Pull request by VinneyJ**
quote `apple-touch-icon` favicon

### CODE REVIEW

**Comment by VinneyJ** [comment]
> Where did you see the **civicSignal** stylisation @VinneyJ ?

isn't the **civic** all lowercase? well, at least I thought I wrote wrong. But yes, I can change it back if it is wrong

**Comment by kilemensi** [comment]
**CiviSignal** (with capital `C`) is the correct styling @VinneyJ.

**Comment by VinneyJ** [comment]
> **CiviSignal** (with capital `C`) is the correct styling @VinneyJ.

Fixed. Thanks for the clarification. @kilemensi

**Comment by kilemensi** [comment]
Lets add the email fix @VinneyJ

**Comment by VinneyJ** [comment]
I saw envs get added when building the release during deployment. What happened is that I exported SUPPORT_URL but not the email. Now that I exported it, it should appear after doing the production build.

**Comment by kilemensi** [comment]
Ah.. cool @VinneyJ then I think we're good. In the mean time, think of a way we can make sure the required env vars are always exported before build

**Review by koechkevin — APPROVED** [review]

**Pull request merged**
